
variables:
  SOURCES_URI: "https://github.com/Elektrobit/"
  ELOS_DEPENDENCY_CONFIG: "ci/dependencies_emlix.json"
  DOCKER_IMAGE: elos-ci:$CI_COMMIT_REF_SLUG
  DOCKER_HOST: "tcp://docker:2375"

workflow:
  auto_cancel:
    on_new_commit: interruptible

stages:
  - docker-image
  - build
  - test

default:
  image: $CI_REGISTRY_IMAGE/$DOCKER_IMAGE
  services:
    - name: docker:24-dind
      alias: docker
      variables:
        DOCKER_TLS_CERTDIR: ""
  tags:
      - "docker"
  interruptible: true

before_script:
  - env | sort

build-docker-image:
  stage: docker-image
  image: ubuntu:jammy
  before_script:
    - apt-get update
    - apt-get install -y docker.io
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE -f ci/Dockerfile
             --build-arg UID=$(id -u) --build-arg GID=$(id -g)
             --build-arg ASMCOV_URI="$ASMCOV_URI"
             ci/
    - docker tag $DOCKER_IMAGE $CI_REGISTRY_IMAGE/$DOCKER_IMAGE
    - docker push $CI_REGISTRY_IMAGE/$DOCKER_IMAGE
      
build-dependencies:
  stage: build
  needs:
    - build-docker-image
  script:
    - ci/install_deps.py --no-tests --no-mocks --verbose
  artifacts:
    paths:
      - build/deps/
    exclude:
      - build/deps/src/
      - build/deps/build/

build-plugins-release:
  stage: build
  needs:
    - build-docker-image
    - build-dependencies
  script:
    - ci/build.sh Release
  artifacts:
    paths:
      - build/Release/dist/

build-plugins-debug:
  stage: build
  needs:
    - build-docker-image
    - build-dependencies
  script:
    - ci/build.sh Debug
  artifacts:
    paths:
      - build/Debug/dist/

smoketests-release:
  stage: test
  needs:
    - build-docker-image
    - build-dependencies
    - build-plugins-release
  script:
    - ci/run_smoketests.sh Release
  artifacts:
    when: always
    paths:
      - build/Release/result/smoketest_results

smoketests-debug:
  stage: test
  needs:
    - build-dependencies
    - build-plugins-debug
  script:
    - ci/run_smoketests.sh Debug
  artifacts:
    when: always
    paths:
      - build/Debug/result/smoketest_results



